# Generated by Django 5.1.7 on 2025-05-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_date_of_birth_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershippingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
