# Generated by Django 5.1.7 on 2025-05-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcolor_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
