# Generated by Django 5.1.7 on 2025-05-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_discount_price_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='price',
        ),
    ]
